
# Site settings
title: "TODO"
baseurl: ""
url: https://inariksit.github.io
repository: inariksit/inariksit.github.io

#avatar: 
#favicon:
#language: en

#
# Icons
#
icons:
#  rss: true
  github: inariksit
#  email: 

#
# Scripts.
#
# disqus:

#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent posts
str_show_all_posts: Show all posts

#
# Recent posts.
#
recent_posts_num: 10

#
# Pagination.
#
paginate: 10
paginate_path: page/:num

#
# Gems.
#
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji

#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
- vendor
theme: jekyll-theme-minimal
