title: Inari Listenmaa
email: inari.listenmaa@gmail.com
author: Inari Listenmaa
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: https://inariksit.github.io # the base hostname & protocol for your site, e.g. http://example.com
github_username:  inariksit
logo: images/logo.png
github:
  is_user_page: true

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
#theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
